version: '3.4'

services:
  document.analyzer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44319
      - AzureSettings__FormRecognizerSubscriptionKey=xx
      - AzureSettings__FormRecognizerEndpoint=xx
      - AzureSettings__StorageCredentialKeyvalue=xx
      - AzureSettings__StorageName=documentanalyzerstorage
      - AzureSettings__TrainingContainerName=training-data-container
      - AWS_ACCESS_KEY_ID=xx
      - AWS_SECRET_ACCESS_KEY=xx
      - AWS_REGION=eu-west-2
      - S3Storage__Bucket=document-analyzer-bucket
    ports:
      - "63264:80"
      - "44319:443"